### ISSUE TITLE
Install error on version 0.4.0

### ISSUE THREAD

**Issue by axelpgr** [sveinbjornt/iceaddr#3]
Other versions install without issue, however when installing 0.4.0 via pip on Windows 10 gives a UnicodeDecodeError:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5242: character maps to <undefined>

**Comment by sveinbjornt** [comment]
Can I get the full error message?

**Comment by axelpgr** [comment]
> Can I get the full error message?

ERROR: Command errored out with exit status 1:
     command: 'c:\users\xxxx\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxxx\\AppData\\Local\\Temp\\pip-install-zd1j8zyj\\iceaddr\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxxx\\AppData\\Local\\Temp\\pip-install-zd1j8zyj\\iceaddr\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xxxx\AppData\Local\Temp\pip-pip-egg-info-y263fbb4'
         cwd: C:\Users\xxxx\AppData\Local\Temp\pip-install-zd1j8zyj\iceaddr\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxxx\AppData\Local\Temp\pip-install-zd1j8zyj\iceaddr\setup.py", line 4, in <module>
        long_description = fh.read()
      File "c:\users\xxxx\appdata\local\programs\python\python38-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 5242: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by sveinbjornt** [comment]
Hmmm, seems to be an issue related to unicode characters in the README file. Will look into it. Don't have a Windows system to test on, though.

**Comment by sveinbjornt** [comment]
Does this persist with the latest version (0.5.1)?

**Comment by sveinbjornt** [comment]
Fixed in master.
