### ISSUE TITLE
Updating the db

### ISSUE THREAD

**Issue by jokull** [sveinbjornt/iceaddr#4]
Are you planning to make new releases with periodical updates to staðfangaskrá? It’s updated every week on the skra.is FTP server. Or are users encouraged to keep their own sqlite db up to date?

**Comment by sveinbjornt** [comment]
I hadn't really given it much thought, but probably periodic updates to the package are in order now that other people seem to be using it! Originally put together for address and placename lookup in Greynir: https://greynir.is/locations

**Comment by axelpgr** [comment]
+1 for periodic updates 😊

**Comment by sveinbjornt** [comment]
I'll try to do period updates. Maybe not monthly, but every few months at least. Those who need more frequent updates can roll their own update mechanism using the database build scripts in the repo.
