### ISSUE TITLE
Most placenames have ISN93 coords?

### ISSUE THREAD

**Issue by hinrikur** [sveinbjornt/iceaddr#8]
Out of the box behaviour (v. 0.5.5, PyPI):

```python
>>> from iceaddr import placename_lookup
>>> placename_lookup('Meðalfellsvatn')
[{'id': 59021, 
'nafn': 'Meðalfellsvatn', 
'flokkur': 'Vatnaörnefni Mið', 
'lat_wgs84': 225798.99670902034, 
'long_wgs84': 2574241.490482475 }]
```

Note the ISN93 lat_wgs84 and long_wgs84 values.

After cloning and running `build_db.py` and `add_placename_data.py`, with latest IS50V data and running the module locally:

```python
>>> from iceaddr import placename_lookup
>>> placename_lookup('Meðalfellsvatn')
[{'id': 58989, 
'nafn': 'Meðalfellsvatn', 
'flokkur': 'Vatnaörnefni Mið', 
'lat_wgs84': 64.31120378256016, 
'long_wgs84': -21.599793276028475}]
```

This matches the intended behaviour.

Looking at the original `iceaddr.db` file, the only placenames with WGS84 coordinates are the ones added manually from `placename_additions.txt`. The rest (160.000+) entries have ISN93 coordinates (I guess? These aren't WGS84 coordinates at least).

@sveinbjornt You mentioned in https://github.com/sveinbjornt/iceaddr/issues/4#issuecomment-709671056_ that you wouldn't be doing regular updates, but this looks like an error from the last commit (f2eb867).

**Comment by sveinbjornt** [comment]
Thanks for the feedback @hinrikur , will fix ASAP!

**Comment by sveinbjornt** [comment]
Fixed in https://github.com/sveinbjornt/iceaddr/releases/tag/0.5.6
